### ISSUE TITLE
global variable "colors_name" to match theme

### ISSUE THREAD

**Issue by AlessandroYorba** [KKPMW/moonshine-vim#1]
`let g:colors_name = "moonshine"` for moonshine.vim
`let g:colors_name = "moonshine_lowcontrast"` for moonshine_lowcontrast.vim
`let g:colors_name = "moonshine_minimal"` for moonshine_minimal.vim 

This is just to avoid any Errors if vim is launched and `colo moonshine_lowcontrast"` or `colo moonshine_minimal` is declared in the .vimrc

**Comment by karoliskoncevicius** [comment]
Thanks a lot! It's done.

Somehow I never had any issues and so forgot to change that..
