### ISSUE TITLE
What License is this under?

### ISSUE THREAD

**Issue by slugbyte** [KKPMW/moonshine-vim#2]
Hi, I love this theme but have made some tweaks because I'm slightly color blind. 
Do you mind if I publish my version to GitHub if I give you credit? 

If not no worries :)

**Comment by karoliskoncevicius** [comment]
Hey,

Feel free to do what you like - changing and adding it to your github is certainly fine.

To make it more official I added the most unrestricted license I could find - "public domain". Hope it covers your needs? :)

**Comment by slugbyte** [comment]
👍 You are amazing, thank you!! I'll do the same :)
